### PR TITLE
api auth using login page creds + url directory

### PR DESCRIPTION
**Pull request by vin047**
Login page authentication for Domoticz requires username and password as url parameters encoded with base64.

In addition, i've added a "directory" attribute which is useful when using a reverse proxy.

### CODE REVIEW

**Comment by madgeni** [comment]
Hi - 
i'm going to leave the blinds alone - we had this discussion on the forum in Oct:
https://www.domoticz.com/forum/viewtopic.php?f=38&t=9446&p=100623&hilit=blinds#p100623

Also - don't really understand your config change? I use login page for auth, and i don't need additional configuration. The config is there to interact with the api, which i don't believe is affected by the security setting in Domoticz for logging on.

**Comment by vin047** [comment]
Hey @madgeni 
Firstly, apologies for putting both commits in the same PR (bit confusing!) - forgot to create separate release branches for them. I'll split them into 2 branches/PRs if you decide to incorporate any of the changes

**Blinds change**
Had a read of the discussion but it seems to corroborate flipping the values (correct me if I've misunderstood the forum posts): https://www.domoticz.com/forum/viewtopic.php?f=38&t=9446&p=100654&hilit=blinds#p100654 - @nigels0 said that
```
Domoticz API switchcmd=On -> Closes blinds
Domoticz API switchcmd=Off -> Open blinds
```
Alexa's TurnOnRequest appears to be triggered by an "open" utterance and TurnOffRequest by a "close" utterance - think this may have been erroneously reversed before (judging from https://www.domoticz.com/forum/viewtopic.php?f=38&t=9446&hilit=blinds&start=260#p104041) but it seems to have been fixed as this is what happens now when I tested it:
```
"Alexa open blinds" -> TurnOnRequest
"Alexa close blinds" -> TurnOffRequest
```
Which makes sense. Therefore:
```
"Alexa open blinds" -> TurnOnRequest -> switchcmd=Off -> Open blinds
"Alexa close blinds" -> TurnOffRequest -> switchcmd=On -> Closes blinds
```

I confirm that this works with my blinds with intended behaviour and probably will now work with @nigels0 too. If theres many others for whom the opposite is true (switchcmd=On -> Open blinds etc) then I agree that its best to leave the blinds code as is, but so far 2/2 configurations appear to support the change.

**Auth change**
My domoticz server does not accept api requests with the user/password embedded using the http basic syntax (http://USER:PASS@host:port). No idea why this is, I get 401 unauthorised, but it works when embedding username & password as parameters in the url. Attempted to minimise disruption to others by adding an "authorisation" key in the config which defaults to "basic".

Finally, I run my server behind a reverse proxy. As domoticz doesn't appear to support this out of the box, added a "directory" key, which is again defaulted to "/" to minimise disruption to yourself/others.

Hope that clears things up a bit!

**Comment by nigels0** [comment]
As nigels0, I confirm the blinds work correctly - the change is not necessary. If you want to change this, do it using Domoticz by reversing the blinds.

**Comment by madgeni** [comment]
Thanks @nigels0 - i'd assumed as no-one was shouting that it was ok :)
Hi @vin047 re: authentication, i'm yet to be convinced this change is necessary - can you try using https, and retesting? Again, as no-one has raised an issue with this so far, i'm loathe to add changes for specific user configurations.

**Comment by vin047** [comment]
@nigels0 tried using "inverted blinds" already - seems to have no effect: switchcmd=On->Closes blinds still. And Alexa sends "TurnOnRequest" when you say "open blinds". Bit surprised it works for you considering what you said here: https://www.domoticz.com/forum/viewtopic.php?f=38&t=9446&hilit=blinds&start=260#p104041. However if Alexa now opens the blinds when you ask her to "open blinds" happy to keep it in my own fork - maybe it's just a peculiarity with my blinds/domoticz/alexa setup/something else...

@madgeni yep using HTTPS already (and tried with HTTP just to be sure) - same issue. Again, if it only affects me, happy to keep in my own fork - although I don't see the harm in adding something that _shouldn't_ break existing config (please confirm by a code review, new to node.js). The reverse proxy change would probably be helpful to others though, but again, it's up to you.

**Comment by madgeni** [comment]
hi @vin047 - i'll leave the blinds as they are - Amazon are slowly adding more functionality to the API (colours/locks most recently), so hopefully they'll clean up the 'Open/Close Up/Down' language soon :)

I'm not averse to your config change - it must be pertaining to your reverse proxy, rather than how the domoticz API handles authentication - but want to keep the configuration clean. Also, and pretty selfishly - i'm hoping to move away from supporting this soon, and encourage people to use www.controlicz.com which facilitates a 'pure' native alexa skill, so people don't have to roll their own.

**Comment by vin047** [comment]
@madgeni sure no worries :) 

controlicz.com looks like a promising solution!

**Pull request closed without merging**
