### PR TITLE
Config

### PR DESCRIPTION
**Pull request by Nesurion**
adds code to read the domoticz config out of a file. This allows using and commiting the code without worrying about commit sensitive data like a password.

To use the config file, rename the _config.json.example_ to _config.json_ and fill out the missing values.

### CODE REVIEW

**Comment by madgeni** [comment]
Thank you!

**Comment by Nesurion** [comment]
I've seen, that you added the changes in master! Thank you.
One last thing though: could you add the 'config.json' to the '.gitignore' to avoid an accidental commit of credentials?

**Comment by madgeni** [comment]
hopefully i’ve done that!
i’ve directly added the files you guys need, so not tested that it’s working yet :)

**Comment by madgeni** [comment]
Took a great idea, and incorporated it :)

**Pull request closed without merging**
